### ISSUE TITLE
[dev] Time out 522 errors

### ISSUE THREAD

**Issue by PierBover** [cloudflare/wrangler-legacy#2077] opened 2021-09-17 16:49 UTC
### 🐛 Bug report

`wrangler dev` only return 522 errors. Seems something is down on Cloudflare's network?

I've updated Wrangler to the latest version 1.19.3.

I've authenticated with `wrangler login` again.

I've created a new `wrangler.toml` using `wrangler init`.

```
name = "player-html"
type = "webpack"
route = '.../*'
zone_id = '...'
usage_model = ''
compatibility_flags = []
workers_dev = false
compatibility_date = "2021-09-17"
```

(I've obfuscated the domain path and zone id)

My worker is running fine when publishing or previewing.

#### Describe the bug

When starting `wrangler dev` and trying to access `http://127.0.0.1:8787` only 522 errors are returned.

#### Reproduce the bug

Start `wrangler dev` try to access any url at `http://127.0.0.1:8787`.

**Comment by PierBover** [comment] 2021-09-17 21:54
Not sure what's going on...

I've created a new worker with `wrangler generate` and it works fine.

It sucks I will need to do `wrangler generate` for all current worker projects and migrate the JS files though.

**Comment by threepointone** [comment] 2021-09-24 17:56
This seems like something we should fix. Opening this back up and assigning this to myself, and I'ld be happy to have a look (either later this weekend, or early next week). Could you possibly share the a script that fails, or even a sample project? If not, I'll try with a simple script myself and see if I can reproduce this.

**Comment by PierBover** [comment] 2021-09-24 20:13
The script really didn't matter as the request never reached it.

For some reason now it's working. Without changing anything on my part nor updating wrangler.

**Comment by threepointone** [comment] 2021-09-24 20:22
Well that's frustrating, and I'm sorry you had to face that experience. I'll close the issue, but I'll keep an eye open for this, and you should feel free to either drop a line here, or file a fresh issue and cc me if it happens to you again. Sorry again!

**Comment by paulgibbs** [comment] 2021-10-06 09:37
I've run into this issue today with `wrangler dev` but I haven't yet made much progress understanding what's going on.

I've had it work, before, but not since updating to Mac OS Big Sur (I can't *think* of anything else I've changed recently).

**Comment by jspspike** [comment] 2023-02-27 16:54
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

**Closed by jspspike** 2023-02-27 16:54 UTC
Labels: bug
