### ISSUE TITLE
`dev` and `preview` produce unhelpful error message when bucket directory is missing

### ISSUE THREAD

**Issue by fluidsonic** [cloudflare/wrangler-legacy#1718] opened 2021-01-12 12:59 UTC
`dev` and `preview` output *Error: No such file or directory (os error 2)* without any further indication on what's wrong. After lot of trial and error I ran `publish` which actually produced a meaningful error message that helped me solve the issue.

```shell
% wrangler build
✨  Built successfully, built project size is 494 KiB.

% wrangler dev
🌀  Using namespace for Workers Site "…"
Error: No such file or directory (os error 2)

% wrangler preview
🌀  Using namespace for Workers Site "…"
Error: No such file or directory (os error 2)

% wrangler publish
✨  Built successfully, built project size is 494 KiB.
Error: ⚠️  bucket directory "release/browser" does not exist
```

wrangler 1.12.3

**Comment by ashleyoldershaw** [comment] 2021-11-25 10:23
Yes! The issue is we need to run `npm export` - hope this helps someone in future!

**Comment by JacobMGEvans** [comment] 2023-02-27 16:51
Thanks for creating this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this PR.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it or create a new PR in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

**Closed by JacobMGEvans** 2023-02-27 16:51 UTC
Labels: interface
