### ISSUE TITLE
Glob and exclude support for `watch_dir` in custom builds

### ISSUE THREAD

**Issue by hmnd** [cloudflare/wrangler-legacy#1829] opened 2021-03-27 00:12 UTC
#### Describe the feature

A clear and concise description of the feature. What problem does it solve for you?

I have a monorepo of workers structured like so:
```
├── package.json
├── packages
│   ├── dbconnect-example
│   │   ├── dist
│   │   │   ├── worker.js
│   │   │   └── worker.js.map
│   │   ├── handler.ts
│   │   ├── index.ts
│   │   ├── package.json
│   │   ├── webpack.config.js
│   │   └── wrangler.toml
```
Because of this structure, a rebuild gets triggered twice on every change when running `wrangler dev`, as output is a subdirectory of the worker's source.
I would like the option to provide a glob pattern to the `watch_dir` option in `[build]`, so that rebuilds are only triggered when `*.ts` files are changed. Alternatively, or in addition, it would be great to have a `watch_dir_exclude` option that can be passed an array of globs to exclude (eg. `watch_dir_exclude = [ "dist", "**/*.js" ]`).

**Comment by xortive** [comment] 2021-04-09 14:08
Could you put your .ts files in a `src` directory, that you could specify as your `watch_dir`, or is the rest of your tooling reliant on your current directory structure such that it's impossible to change?

**Comment by hmnd** [comment] 2021-04-13 09:31
@xortive I can pretty easily, so I'm doing that for now. However, it's pretty typical for code to be stored at the root of each project's directory in monorepos, so glob support would still be appreciated.

**Comment by hmnd** [comment] 2021-04-19 04:53
@xortive just found another use case for this: I've got an `src/` folder to contain my worker's code, but now that I need to build and serve some static client-side JS (with workers sites), I've got a `static/` folder as well. Not having glob/exclude/include support means I can only set it to watch either `src/` or `static/`, but not both.

**Comment by kavika-1** [comment] 2021-09-30 00:33
Similar problem: have workspaces with a /packages/... folder for shared code and a /workers/... folder.  Want to watch both folders for changes.  Watching the root causes the multiple rebuilds.  So excluding "dist" folder(s) would work.  Another approach might be to have addition watch folders.  Thus, whatever the default is (src ?) works great, but then allow adding additional folders to watch.

**Comment by penalosa** [comment] 2023-02-27 16:53
Thanks for suggesting this feature! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.

New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If this is a feature you’d like to see in wrangler v2+, please feel free to report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

**Closed by penalosa** 2023-02-27 16:53 UTC
Labels: feature, investigate, custom builds
