### ISSUE TITLE
`wrangler dev` in 11.0 is non-functional when there are deployed workers with non-specific routes

### ISSUE THREAD

**Issue by TehShrike** [cloudflare/wrangler-legacy#1546] opened 2020-09-04 17:41 UTC
### 🐛 Bug Report

I have a worker deployed with a very broad/non-specific route, `*example.com/*`.  It handles some generic redirect behavior.

I have other workers with more specific routes, e.g. `https://subdomain.example.com/path/*`.

This works fine, thanks to Cloudflare Workers' [route matching behavior](https://developers.cloudflare.com/workers/platform/routes#matching-behavior) where the most specific routes are matched first.

However, as of wrangler 11.0, I am unable to test my workers with more specific routes.  I run `wrangler dev` and everything starts up fine, but when I make GET requests to `http://127.0.0.1/path/anything`, those requests are handled by the `*example.com/*` worker in production.

**This is a bug.**  At the very least, the route matching rules should be applied, using the `route`/`routes` in my `wrangler.toml` file.

**This is concerning.**  It makes me very nervous that my HTTP requests to `127.0.0.1` could be handled by production workers.  This implies that if I'm `POST`ing to localhost with a valid `Authorization` header, I could be causing side effects in production.

I do not want/expect requests to localhost to be proxied to unrelated deployed production code.

#### Environment

* operating system: macOS
* output of `rustc -V`: ﻿`-bash: rustc: command not found`
* output of `node -v`: `v14.8.0`
* output of `npx wrangler -V`: `👷 ✨  wrangler 1.11.0`
* contents of `wrangler.toml`

**Comment by caass** [comment] 2020-09-19 00:23
I think this is related to an issue I'm getting, so I'll comment here to avoid opening a duplicate issue.

Steps to reproduce:

1. Create a new wrangler project with `wrangler generate example https://github.com/cloudflare/worker-template`
2. `cd` in and observe that `wrangler dev` works
3. Add a route to `wrangler.toml` that includes a wildcard (e.g. `route = somesite.com/*`)
4. try `wrangler dev` again

This happens whether the `route` or `routes` key is specified.

**Comment by TehShrike** [comment] 2020-09-19 23:48
@caass for thoroughnesses sake, what is your expected behavior after step 4, and what are you seeing instead of that?

**Comment by caass** [comment] 2020-09-20 01:02
> @caass for thoroughnesses sake, what is your expected behavior after step 4, and what are you seeing instead of that?

I edited my comment to put the expected behavior, as well as what actually happens :)

**Comment by ashleymichal** [comment] 2020-09-25 16:15
note: status - needs repro indicates that we'd like a member of our team to reproduce; thank you for the detailed report!

**Comment by emesterhazy** [comment] 2020-10-14 16:27
Thanks for posting this @TehShrike - I have the same issue as you. I can't test workers that match on subdomains with dev because all requests to localhost are forwarded to the production server for the bare domain.

**Comment by lid** [comment] 2021-01-09 19:52
I have this issue as well; looks like a workaround is to set `workers_dev = true` in wrangler.toml - in this case the worker will respond, and prevents the request from being forwarded to the production server for the bare domain.

**Comment by jamesarosen** [comment] 2021-02-26 01:09
> I have this issue as well; looks like a workaround is to set workers_dev = true in wrangler.toml

With `wrangler@1.13.0`, I've found I _also_ need to delete the `route` or `routes` in `wrangler.toml`. It's annoying to have to make those changes when developing locally then revert them before publishing.

**Comment by TehShrike** [comment] 2021-05-26 16:24
Any update on this?  This is still killing us when trying to develop workers.  Why was #1623 closed?

**Comment by quarties** [comment] 2021-07-09 23:59
same issue
`macOS 11.4` / `wrangler 1.17.0` (I also tried latest beta) / `node v14.17.0`

reverting to `1.10.X` fixes it, but I would like to avoid using legacy verions 😞 any news on this?

my `wrangler.toml`
```
# top level configuration
type = "javascript"
account_id = "xxx"
zone_id = "xxx"
usage_model = "bundled"
name = "woocommerce-product-cards-staging"
route = "woocommerce.staging.livechat.expert/*"
kv_namespaces = [
    { binding = "STORES", id = "xxx", preview_id = "xxx" },
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[dev]
ip = "127.0.0.1"
port = 8080
local_protocol="http"
upstream_protocol="https"

# environment configuration
[env.production]
workers_dev = true
name = "woocommerce-product-cards"
route = "woocommerce.livechat.expert/*"
kv_namespaces = [
    { binding = "STORES", id = "xxx" },
]
```

**Comment by danbars** [comment] 2021-12-24 21:51
Any news on this?
Still happens with wrangler 1.19.6
As mentioned by @jamesarosen  it is still needed to comment-out `route` and set `workers_dev` to true every time you develop locally.

**Comment by jgentes** [comment] 2021-12-28 18:11
@danbars do you see this while using Miniflare?

**Comment by danbars** [comment] 2021-12-28 19:14
@jgentes I don't use Miniflare.
It started once I've defined a route on my custom domain.
The route that I've defined ends with `/*`.

**Comment by jgentes** [comment] 2021-12-29 14:42
Could you try https://github.com/cloudflare/miniflare to see if that is a viable workaround?

**Comment by jspspike** [comment] 2023-02-27 16:55
Thanks for reporting this issue! Wrangler v1 is now deprecated and support is only being provided for critical updates or security concerns. As such, we are closing this issue.
New versions of Wrangler are maintained in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). If you are running into a similar issue with wrangler v2, please report it in the [workers-sdk repo](https://github.com/cloudflare/workers-sdk). For more info about wrangler v1 deprecation, please check out our [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1).

**Closed by jspspike** 2023-02-27 16:55 UTC
Labels: bug, investigate, dev
